# Generated by Django 5.2.6 on 2025-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
